<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/fontawesome.min.css'))
            ->prependStylesheet($this->basePath('css/all.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
        ?>
        
        <?= $this->navigation('Laminas\Navigation\Default')->links().PHP_EOL ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" height="28" alt="Laminas MVC Skeleton"/>&nbsp;Laminas MVC Skeleton
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?= $this->navigation('Laminas\Navigation\Default')->menu()
                        ->setMaxDepth(2)
                        ->setPartial('application/_shared/menu')
                        ->setRenderInvisible(false)
                        ->renderPartialWithParams(
                            [
                                'user' => $this->user
                            ]
                        )
                    ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="breadcrumb">
                <?= $this->navigation('Laminas\Navigation\Default')->breadcrumbs()
                    ->setLinkLast(false)
                    ->setMinDepth(0)
                    ->setMaxDepth(5)
                    ->setSeparator(' / ')
                    ->render()
                ?>
            </div>
            
            <?= $this->content ?>
            
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> "Laminas: Build Enterprise Websites" - Adam Omelak.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
