<?php

/**
 * Configuration file generated by Laminas API Tools Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return array(
    'Laminas\Navigation',
    'Laminas\\Serializer',
    'Laminas\\Paginator',
    'Laminas\\Di',
    'Laminas\\Log',
    'Laminas\\Db',
    'Laminas\\Mvc\\Plugin\\FilePrg',
    'Laminas\\Mvc\\Plugin\\FlashMessenger',
    'Laminas\\Mvc\\Plugin\\Identity',
    'Laminas\\Mvc\\Plugin\\Prg',
    'Laminas\\Session',
    'Laminas\\Mvc\\I18n',
    
    'Laminas\\Form',
    'Laminas\\Hydrator',
    'Laminas\\InputFilter',
    'Laminas\\Filter',
    'Laminas\\I18n',
    'Laminas\\Cache',
    'Laminas\\Router',
    'Laminas\\Validator',
    'Laminas\\DeveloperTools',
    'Laminas\\ApiTools\\ApiProblem',
    'Laminas\\ApiTools\\ContentNegotiation',
    'Laminas\\ApiTools\\Rpc',
    'Laminas\\ApiTools\\MvcAuth',
    'Laminas\\ApiTools\\Hal',
    'Laminas\\ApiTools\\Rest',
    'Laminas\\ApiTools\\ContentValidation',
    'Laminas\\ApiTools',
    'Laminas\\ApiTools\\Configuration',
    'Laminas\\ApiTools\\Admin',
    'Laminas\\ApiTools\\Documentation',
    'Application',
    'ApplicationApi',
    'ZfcAdmin',
    'Admin',
    'LmcRbacMvc',
);
