<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/fontawesome.min.css'))
            ->prependStylesheet($this->basePath('css/all.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" height="28" alt="Laminas MVC Skeleton"/>&nbsp;Laminas MVC Skeleton
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item <?= $this->controller === Application\Controller\IndexController::class ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                        </li>
                        
                        <li class="nav-item <?= $this->controller === Application\Controller\UsersController::class ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('users') ?>">Users</a>
                        </li>
                        <li class="nav-item <?= $this->controller === Application\Controller\ComicsController::class ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('comics') ?>">Comics</a>
                        </li>
                        <li class="nav-item <?= $this->controller === Application\Controller\PollingController::class ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('polling') ?>">Poll</a>
                        </li>
                        <li class="nav-item <?= $this->controller === Application\Controller\FormsController::class ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('forms') ?>">Forms</a>
                        </li>
                        <?php if ($this->user): ?>
                            <li class="nav-item <?= $this->controller === Application\Controller\UserController::class ? 'active' : '' ?>">
                                <a class="nav-link" href="<?= $this->url('user')?>">My Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('login', ['action' => 'logout'])?>">Logout</a>
                            </li>
                        <?php else: ?>
                            <li class="nav-item <?= $this->controller === Application\Controller\RegisterController::class ? 'active' : '' ?>">
                                <a class="nav-link" href="<?= $this->url('register')?>">Registration</a>
                            </li>
                            <li class="nav-item <?= $this->controller === Application\Controller\LoginController::class ? 'active' : '' ?>">
                                <a class="nav-link" href="<?= $this->url('login')?>">Log-in</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> "Laminas: Build Enterprise Websites" - Adam Omelak.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
