<div class="jumbotron">
    <h1><span class="zf-green">Comics</span></h1>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Cover</th>
        </tr>
        <?php foreach ($comics as $rowModel): ?>
            <tr>
                <td><?= $rowModel->getId() ?></td>
                <td><?= $rowModel->getTitle() ?></td>
                <td><img src="<?= $rowModel->getThumbUrl() ?>" /></td>
            </tr>
        <?php endforeach; ?>
    </table>

    <?= $this->paginationControl(
        $comics,
        'Sliding',
        'pagination_search',
        ['route' => 'comics/paginator']
    ) ?>
</div>
